name: docu_tools
description: A new Flutter project for smart file management.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^10.3.3
  intl: ^0.20.2
  file_saver: ^0.3.1
  universal_html: ^2.2.4
  flutter_image_compress: ^2.3.0
  pdf: ^3.10.8
  printing: ^5.14.0
  http: ^1.2.1
  shared_preferences: ^2.2.3 # Or any recent version
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # --- ADD THIS SECTION ---
  assets:
    - assets/logo.png
